apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default  # Application belongs to the default project
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 5.25.1
    chart: kube-state-metrics
    helm:
      releaseName: kube-state-metrics
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
