apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 62.6.0  # Prometheus Operator Helm Chart version (adjust as necessary)
    chart: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Automatically create the monitoring namespace if it doesn't exist
  helm:
    values: |
      prometheus:
        prometheusSpec:
          serviceMonitorSelectorNilUsesHelmValues: false
