apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default  # Application belongs to the default project
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.27.0
    chart: prometheus
    helm:
      releaseName: prometheus
      values: |
        kube-state-metrics:
          enabled: true
        prometheus-pushgateway:
          enabled: false
        prometheus-node-exporter:
          enabled: true
        serverFiles:
          alerting_rules.yml:
            groups:
            - name: quizengine
              rules:
              - alert: TooManyRestarts
                expr: kube_pod_container_status_restarts_total{container="quizchecker"} > 1
                labels:
                  severity: critical
                  team: sre
                for: 5s
                annotations:
                  summary: "Too many restarts"
                  description: "Quizchecker seems to be restarting too much"
        alertmanager:
          enabled: true
          config:
            receivers:
              - name: default-receiver
                slack_configs:
                  - channel: '@quizengine'
                    send_resolved: true
                    text: |
                      {{.CommonAnnotations.summary}}
                      {{.CommonAnnotations.description}}
                    api_url: 'https://hooks.slack.com/services/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'

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
