apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default  # Application belongs to the default project
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.27.0
    chart: prometheus
    helm:
      releaseName: prometheus
      values: |
        kube-state-metrics:
          enabled: true
        prometheus-pushgateway:
          enabled: false
        prometheus-node-exporter:
          enabled: true
        serverFiles:
          alerting_rules.yaml:
            groups:
              - name: quizengine
                rules:
                  - alert: Replicas going down
                    expr: kube_deployment_spec_replicas{deployment="quizchecker"} > kube_deployment_status_replicas{deployment="quizchecker"}
                    labels:
                      severity: critical
                      team: sre
                    for: 5s
                    annotations:
                      summary: "Fewer replicas than in spec"
                      description: "We are running quizchecker with lesser replicas than needed"
        alertmanager:
          enabled: true
          config:
            receivers:
              - name: default-receiver
                slack_configs:
                  - channel: '#demo-alerts'
                    send_resolved: true
                    text: |
                      {{.CommonAnnotations.summary}}
                      {{.CommonAnnotations.description}}
                    api_url: 'https://hooks.slack.com/services/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'

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
