apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  project: default  # Application belongs to the default project
  source:
    repoURL: https://github.com/kmflow-org/kmflow.git
    targetRevision: main
    path: infra/apps
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
