plugin: amazon.aws.aws_ec2
aws_profile: kmflowdev
regions:
  - us-west-2
filters:
  tag:env: dev
keyed_groups:
  - key: tags.env
    prefix: env
hostnames:
  - instance-id
compose:
  ansible_host: instance_id
  ansible_user: '"ssm-user"'
